# Generated by Django 5.1.3 on 2024-12-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
